const skills = [
  {
    title: 'Skillsets',
    items: [
      'Systems Architecture',
      'Cloud Architecture',
      'Design Systems',
      'Building Mobile Apps (iOS & Android)',
      'Embedded Systems',
      'Building Desktop Apps',
      'IoT',
      'Microservices',
      'Unit testing',
      'E2E testing',
      'Product Development',
      'Progressive Web Apps',
      'Prototyping',
      'MPA',
      'SPA',
      'Jamstack',
      'Serverless',
      'Building integrations',
      'Web Services',
      'Data Extraction',
      'eCommerce',
    ],
  },
  {
    title: "APIs I've integrated with",
    items: [
      'Stripe',
      'Twilio',
      'Mapbox',
      'GoogleMaps API',
      'Pusher',
      'Stytch',
      'Auth0',
      'Magic',
      'WorkOS',
      'OpenAI',
      'Hanko',
      'Microsoft Graph API',
    ],
  },
  {
    title: "Backend tools I've used",
    items: ['Nuxt', 'TRPC', 'Express', 'Flask', 'Node', 'Nitro'],
  },
  {
    title: "Datastores I've used",
    items: [
      'DynamoDB',
      'MySQL',
      'NoSQL',
      'SQLite',
      'PlanetScale',
      'Cloudflare D1',
      'Postgres',
    ],
  },
  {
    title: "Frontend tools I've used",
    items: [
      'Tailwind CSS',
      'Vue',
      'NuxtUI',
      'Tauri (iOS, Android, & Desktop targets)',
      'React Native',
      'DaisyUI',
      'Oruga',
      'Vuetify',
      'Bootstrap',
      'Material Design',
      'SCSS',
      'UnoCSS',
      'Bulma',
      'Next.js',
      'React.js',
      'Shadcn',
      'Tanstack Query',
    ],
  },
  {
    title: "Infrastructure I've used",
    items: [
      'Cloudflare Durable Objects',
      'Cloudflare Workers',
      'AWS IAM',
      'AWS Lambda',
      'AWS S3',
      'Cloudflare',
      'DigitalOcean',
      'Heroku',
      'Netlify',
      'AWS Secrets Manager',
      'Doppler',
    ],
  },
  {
    title: "Languages I've used",
    items: [
      'TypeScript',
      'JavaScript',
      'Rust',
      'Python',
      'HTML',
      'SQL',
      'Golang',
      'YAML',
      'XML',
    ],
  },
  {
    title: "Tools I've used",
    items: [
      'Git',
      'NPM',
      'Yarn',
      'Bun',
      'pnpm',
      'Vite',
      'VSCode',
      'Neovim',
      'Docker',
      'Nix',
      'Terminal',
      'Jest',
      'Vitest',
      'Playwright',
      'GitHub',
      'GitLab',
      'Sentry',
    ],
  },
]
const workHistory = [
  {
    companyName: 'Denari (funded AI startup) (2025-2025)',
    role: 'Data Engineer (Contract)',
    tldr: [
      'Independently built a greenfield MVP for a new product line',
      'Collaborated with technical and non-technical stakeholders',
      'Built a fully automated data ingestion and processing pipeline',
      'Created data visualization dashboard with single sign-on via Microsoft Entra',
    ],
    tools: [
      'TypeScript',
      'React',
      'Next.js',
      'WorkOS',
      'Microsoft Graph API',
      'Postgres',
      'Drizzle',
    ],
  },
  {
    companyName: 'InternalStack (2024 - 2025) (Spinoff project from OrderDive)',
    role: 'Software Engineer',
    tldr: [
      'Built a DX-focused SDK in TypeScript',
      'Built an (experimental) fully automated envelope encryption microservice',
      'Built a B2B SaaS platform with billing, SSO, and developer portal',
      'Created in-depth developer-facing documentation',
    ],
    tools: [
      'TypeScript',
      'Cloudflare D1',
      'Cloudflare Queues',
      'Cloudflare Workers',
      'Nuxt',
      'WorkOS',
      'TRPC',
      'SQLite',
      'Drizzle',
    ],
  },
  {
    companyName: 'CheetahBooking (2023 - 2024) (Co-founded)',
    role: 'Chief Technology Officer (CTO)',
    tools: ['TypeScript', 'MySQL', 'Nuxt'],
    tldr: [
      'Built a B2B SaaS MVP on a very tiny budget',
      'Built an automated scheduling engine',
      'Built a very intuitive form builder',
      'Implemented our CI/CD pipeline with E2E test coverage',
      'Converted Figma designs into a pixel-perfect functional application',
    ],
  },
  {
    companyName: 'OrderDive  (2017 - Present) (Founded)',
    role: 'Software Engineer',
    tools: [
      'TypeScript',
      'Linux',
      'Vercel',
      'Cloudflare Workers',
      'MQTT',
      'Tailwind',
      'Nuxt',
      'TRPC',
      'Vue',
      'MySQL',
    ],
    tldr: [
      'Created a cloud connected ticket printer',
      'Created a sandboxed design system that allowed for in-depth white-labeling',
      'Provisioned and maintained MQTT broker nodes',
      'Created a reservation microservice with dynamic schedule capacity and daylight-savings immunity',
      'Created a restaurant owner dashboard and menu editor',
      'Created the customer facing restaurant online ordering flow',
      'Created AI/LLM-powered tools to help business owners to generate marketing copy',
    ],
  },
  {
    companyName: 'Personal projects',
    role: 'Software Engineer',
    tools: ['Tauri (Mobile & Desktop)', 'Golang', 'Rust', 'TypeScript'],
    tldr: [
      'Created & published an app built with React Native for cosplayers to trigger sound effects usings a concealed bluetooth device',
      'Created a desktop app (Linux, Windows, & Macos) and self-hostable server for syncing emulated retro game save files across devices (Looking to open source it soon)',
      'Created a system tray utility app in Golang (Go) for Macos to quickly find the server process that is blocking my development server port. The program finds the clogged port and kills the parent process.',
    ],
  },
]

export default defineEventHandler(async () => {
  return { skills, workHistory }
})
